[connections.gsheets]
spreadsheet = "19ShjfcP7T3PzcVN1JXeaMyD-P61WTI20HaP5JQfLqRM"

[connections.gsheets.configuration]
type = "service_account"
project_id = "yotei-498110"
private_key_id = "c41ecdbfcdc2e3ecbae00d0cc20f032fcd03c4a1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDYrYuKEvgbMg/6
Aeavzg60n7aZqjUbA0YZDGtzHQ0UiJgIt/Mh19G0lo+PG825Qx3mwmMCIBtSKcGt
/32EAhGMjyA4JmqIM+3Zy1RKHb2n7mzW10+LmzgWe+pkCgqBgOVLf20B9fPz7ZGP
ccJ5/6wsAF5Ktf/VCBB9W08aiIo6TjxdxIafmlkrTYQNn9GBAMMjYw2JBqOfwzJQ
RXaOYk4bxWpizmyvmZK/Pc2iT7ndu0duKAKir5f9MAgIzmgTetJ3WO96EfCQKS+l
apKN4mPzDaudvzM1gduGhWxs1Dl5vbq3yn/0tuQVYehUi/1sxPZp202EAeT3l0Xi
BNFG8BnjAgMBAAECggEAEMpd+kyfAkh+WXLFRBFVLWUE+uJoLBg0WeOO/gQdy94L
3f0XL6OwQey64i2W4wjS69tbXcJMK7FFq2yVduHMJ1a9+evsLHLNtydc+ENWu4kr
0PgtV1WnYoKmtqraho+M9S1CLrk29suNkI6Rse+AkYZTyDlTQlhWIsitGBLFl1/t
JCLy7IFV7YaD0KROWv+BF1yMSs6C1v1MFvu76C29UXZLbbFdoCHG7SyzA+YsLgr4
OXmO4sccrtP4omlDScLNNx7VWE89xRkDbE3UEHchNREUIJJcHMBkCbZlZcPK1ffm
yYESA0CseHmj4uLVX8hihIpZ6dGNks/nSRDA3bWrsQKBgQDyjeycioVLaDHqjVNa
hpQVG8Up49+7rL/55YWAMr/KIHu79nwD2HGDUUljYJuiNn/LwVBaS9KluhMnqr3x
8j6fWW+zUuQmHIqkRem1W2G5TrFZsYkUANi95xZBoWS5wOhvBsvz+N55hKY/mLDQ
2WO4oZ/uzydOQwHUmVTVr/fI8QKBgQDksGi8Nn10DFREU/VO9rOMvdyqVn/RxPuN
5VPEDfkXqyhd5WN08EpCcggQmZtJknTcHA4BSySnj0W8B13hBSC6att5pPGmPb5T
dDVotqOQ2R++i6379ujxj3u2nrarty7VaZKSHgnHvPYDmA4S3IjsRnYshCK6k/ID
UbVnt88wEwKBgGJXDmaNduuSzCInuHLMe39vaenI/O3vZUphN1Y5vS6rKt+TWMaK
W8N9En8bLR6AcCHhN73UXgxZO+jqPea5a5BZx4LyCZQ2IDPoMJAaA64I7LjL1SLq
EPY1mf1z/Q2e294f6FL7ROAJ2wmP06hpaxfxV5GQJYSCgFx86jtVA+ZRAoGARLYI
UfyhRvvpWbpMK1SOcAwfwAJLV1CzMFgmCfMU05q2fzfL4TfNaBdw+uPcN4fMmtHH
F3ZnZfzzO+KOv2xWAAzZMrxvar6Eb/irj3HIxV2nXw4C0YDHTsUIq78WLZPVe4PD
6SkjUSMiW8QU/m/KqAsnuIpfEOYgwgSL18TveIcCgYAIXSYbeEfvPX4+CmuDess+
OWFGcDVsrvCy8wOLR+APPQtIFdfQc/nbfTrD7R3pffIS7j1IuzCsIkQV2uxbsnGl
nqdeRHC0TGd/GwOrdeH647Px/9wysio3kpR/EaohVKMLgOQs0yfQXrUloFm9iCIlU
RyTDBZ9FNl+KcCfsI16EDQ==
-----END PRIVATE KEY-----"""
client_email = "apuri-907@yotei-498110.iam.gserviceaccount.com"
client_id = "109147841725632376585"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/apuri-907%40yotei-498110.iam.gserviceaccount.com"